In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [2]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']

pima = pd.read_csv("diabetes.csv", header=1, names=col_names)

In [3]:
pima.head()

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         1       85  66    29        0  26.6     0.351   31      0
1         8      183  64     0        0  23.3     0.672   32      1
2         1       89  66    23       94  28.1     0.167   21      0
3         0      137  40    35      168  43.1     2.288   33      1
4         5      116  74     0        0  25.6     0.201   30      0

In [5]:
# split dataset in features and target variable
features_cols = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age']
x = pima[features_cols] # features
y = pima.label # target variable

In [6]:
x, y

(     pregnant  glucose  bp  skin  insulin   bmi  pedigree  age
 0           1       85  66    29        0  26.6     0.351   31
 1           8      183  64     0        0  23.3     0.672   32
 2           1       89  66    23       94  28.1     0.167   21
 3           0      137  40    35      168  43.1     2.288   33
 4           5      116  74     0        0  25.6     0.201   30
 ..        ...      ...  ..   ...      ...   ...       ...  ...
 762        10      101  76    48      180  32.9     0.171   63
 763         2      122  70    27        0  36.8     0.340   27
 764         5      121  72    23      112  26.2     0.245   30
 765         1      126  60     0        0  30.1     0.349   47
 766         1       93  70    31        0  30.4     0.315   23

 [767 rows x 8 columns],
 0      0
 1      1
 2      0
 3      1
 4      0
       ..
 762    0
 763    0
 764    0
 765    1
 766    0
 Name: label, Length: 767, dtype: int64)

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [11]:
x.head()

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age
0         1       85  66    29        0  26.6     0.351   31
1         8      183  64     0        0  23.3     0.672   32
2         1       89  66    23       94  28.1     0.167   21
3         0      137  40    35      168  43.1     2.288   33
4         5      116  74     0        0  25.6     0.201   30

In [14]:
logistic_r = LogisticRegression(max_iter=1000)
# fit model wid data
logistic_r.fit(x_train, y_train)

y_pred = logistic_r.predict(x_test)

### Model Evaluation using confusion Matrix

In [17]:
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[118,  13],
       [ 27,  34]])

In [18]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1:", metrics.f1_score(y_test, y_pred))

Accuracy: 0.7916666666666666
precision: 0.723404255319149
Recall: 0.5573770491803278
F1: 0.6296296296296297